-- 《忽了个悠》风险事件初始数据
USE huolegeyou;

-- ============================================
-- 反诈科普数据 (先插入科普，事件表会关联)
-- ============================================
INSERT INTO antiFraudKnow (know_id, title, content, verify_question, related_event_ids) VALUES
(1, '冒充公检法诈骗揭秘', '公检法机关不会通过电话、QQ、微信等社交工具办案，更不会要求转账到"安全账户"。凡是自称公检法要求转账的都是诈骗！记住：真警察不会电话办案，安全账户不存在，转账要求必是诈。', '{"question":"公检法机关会通过什么方式要求你转账到安全账户？","options":["A. 电话通知","B. 微信联系","C. 从来不会","D. QQ 告知"],"answer":"C"}', '["GJF001","GJF002"]'),
(2, '兼职刷单陷阱', '所有刷单都是违法的！前期小额返利只是诱饵，后期大额投入必被骗。记住：刷单=诈骗，垫付=送钱，高回报=高风险。天上不会掉馅饼，踏实工作最靠谱。', '{"question":"关于刷单兼职，以下说法正确的是？","options":["A. 前期都能赚钱","B. 所有刷单都是诈骗","C. 大额刷单才危险","D. 熟人介绍就安全"],"answer":"B"}', '["JZ001","JZ002","JZ003"]'),
(3, '杀猪盘恋爱诈骗', '网恋需谨慎，谈钱必是诈！骗子会打造完美人设，与你建立恋爱关系后诱导投资、借钱。记住：网恋不见面、转账拉黑你、高回报平台都是假。', '{"question":"网恋对象向你推荐投资理财平台，应该？","options":["A. 立即投资","B. 先投小额试试","C. 拒绝并举报","D. 拉上朋友一起"],"answer":"C"}', '["SZP001","SZP002"]'),
(4, '虚假购物诈骗', '网购请选择正规平台！私下交易、提前付款、超低价商品都是陷阱。记住：脱离平台无保障，提前付款钱难追，低价诱惑是陷阱。', '{"question":"二手平台交易时，以下哪种行为最安全？","options":["A. 微信直接转账","B. 平台担保交易","C. 银行提前汇款","D. 现金面交最安全"],"answer":"B"}', '["GW001","GW002","GW003"]'),
(5, '中奖退税骗局', '天上不会掉馅饼！所有"中奖""退税"要求先交钱的都是诈骗。记住：中奖不用先交钱，退税不会私下办，官方渠道最安全。', '{"question":"收到中奖短信要求交手续费，应该？","options":["A. 立即交费领大奖","B. 先交小额试试","C. 直接删除不理","D. 打电话确认"],"answer":"C"}', '["ZJ001","ZJ002"]'),
(6, '仿冒网站 APP 诈骗', '钓鱼网站模仿正规平台，窃取你的账号密码和资金。记住：核对网址很重要，官方应用店下载，陌生链接不要点。', '{"question":"如何识别仿冒网站？","options":["A. 看页面是否漂亮","B. 核对网址域名","C. 看有没有客服","D. 试着重试几次"],"answer":"B"}', '["FM001","FM002"]'),
(7, '冒充亲友诈骗', '骗子冒充亲友借钱，利用你的关心实施诈骗。记住：转账之前必核实，语音视频辨真伪，紧急情况找本人。', '{"question":"收到"朋友"微信借钱，第一步应该？","options":["A. 立即转账","B. 打电话核实","C. 问清楚用途","D. 先转一半"],"answer":"B"}', '["QQ001","QQ002"]'),
(8, '校园贷陷阱', '校园贷利息高、套路深，一旦陷入难以脱身。记住：正规贷款看资质，校园贷多高利贷，量入为出莫超前。', '{"question":"关于校园贷，以下说法正确的是？","options":["A. 无抵押很方便","B. 利息低压力小","C. 多为高利贷陷阱","D. 学生都可以申请"],"answer":"C"}', '["XYD001","XYD002"]'),
(9, '网络游戏交易诈骗', '游戏账号、装备交易请选择官方平台。私下交易、代练充值、低价点券都是陷阱。记住：官方渠道最安全，私下交易风险高，代练充值多骗局。', '{"question":"购买游戏装备，最安全的做法是？","options":["A. 游戏内直接交易","B. 微信联系卖家","C. 先付款后发货","D. 找代练帮忙"],"answer":"A"}', '["YX001","YX002"]'),
(10, '征信诈骗揭秘', '骗子冒充客服称你"征信有问题"，诱导你贷款转账。记住：征信无法人为修改，客服不会让你贷款，转账操作必是诈。', '{"question":"接到电话说你征信有问题，应该？","options":["A. 按对方指导操作","B. 挂断电话核实","C. 立即转账修复","D. 提供个人信息"],"answer":"B"}', '["ZX001","ZX002"]');

-- ============================================
-- 风险事件数据 (30+ 条，覆盖 6 大诈骗类型)
-- ============================================

-- === 冒充公检法类 (GJF) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('GJF001', '社交聊天类', '冒充公检法诈骗', 'Spoofing', 3, '社交福利场景', 1, '警察来电', '【微信来电】陌生号码，接通后对方自称市公安局刑警队，说你的银行卡涉嫌洗钱案，需要配合调查。对方准确说出你的姓名和身份证号，要求你添加"警官"QQ，并下载"安全防护"APP 进行资金核查。', '{"type":"chat","avatar":"police_fake","bg":"chat_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 1),
('GJF002', '弹窗类', '冒充公检法诈骗', 'Information', 3, '校园权限场景', 1, '安全账户通知', '【系统弹窗】你收到一条"最高人民检察院"发来的消息：您的账户涉及重大案件，需立即将资金转入安全账户接受审查，审查结束后全额返还。下方有"立即转账"和"了解详情"按钮。', '{"type":"alert","style":"official_fake","icon":"seal"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 1);

-- === 兼职刷单类 (JZ) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('JZ001', '交互事件类', '虚假购物投资诈骗', 'Kickback', 3, '校园兼职场景', 1, '刷单兼职邀请', '你在兼职群看到消息："足不出户，日赚 300-500 元！只需帮商家刷销量，每单佣金 15-30 元，多劳多得！"对方让你先垫付 100 元试水，承诺立刻返还 115 元。', '{"type":"task","style":"group_msg","highlight":"日赚 300-500"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 100, 100, 100, 0.8, 2),
('JZ002', '社交聊天类', '虚假购物投资诈骗', 'Yank', 3, '校园兼职场景', 2, '大额刷单任务', '刷单客服联系你："亲，前面小额任务完成得很好！现在有个大单，垫付 3000 元，佣金 15% 即 450 元，做完这单就能提现全部收益。"并发来"成功提现"的截图。', '{"type":"chat","avatar":"kefu_fake","bg":"chat_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 3000, 150, 3000, 0.5, 2),
('JZ003', '文档表单类', '虚假购物投资诈骗', 'Information', 2, '校园兼职场景', 1, '兼职信息登记表', '某"正规兼职平台"要求你填写详细个人信息才能接单：姓名、身份证、手机号、银行卡号、支付宝账号、手持身份证照片。声称用于"实名认证和工资发放"。', '{"type":"form","style":"registration","fields":["姓名","身份证","手机号","银行卡","支付宝","手持身份证"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 2);

-- === 杀猪盘类 (SZP) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('SZP001', '社交聊天类', '交友恋爱诈骗', 'Kickback', 3, '社交福利场景', 2, '网恋对象推荐投资', '认识两周的"完美恋人"突然说："我有个内部投资渠道，年化收益 30%，我带你一起赚钱，为了我们的未来。"发来一个看起来很高大上的投资平台链接。', '{"type":"chat","avatar":"lover_fake","bg":"romantic_bg","emotion":"关心"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 5000, 150, 5000, 0.6, 3),
('SZP002', '场景界面类', '交友恋爱诈骗', 'Spoofing', 3, '基础金融场景', 3, '虚假投资平台', '你点开"恋人"推荐的投资平台，界面精美，显示"已盈利 8888 元"，但提现时提示"需缴纳 20% 个人所得税"。客服说缴税后本金收益一起到账。', '{"type":"interface","style":"investment_fake","elements":["盈利显示","提现按钮","缴税提示"]} ', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 2000, 150, 2000, 0.7, 3);

-- === 虚假购物类 (GW) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('GW001', '弹窗类', '虚假购物诈骗', 'Low-cost', 2, '二手交易场景', 1, '超低价二手手机', '二手平台看到：iPhone 15 Pro，99 新，仅售 2000 元（市场价 8000+）。卖家说"急用钱，给钱就卖"，要求微信私下交易，不走平台担保。', '{"type":"product","style":"secondhand","price_highlight":"2000 元"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 2000, 100, 2000, 0.5, 4),
('GW002', '社交聊天类', '虚假购物诈骗', 'Information', 2, '二手交易场景', 1, '卖家要求提前确认收货', '闲鱼买东西，卖家说："我急用钱，你先确认收货，我马上发货，给你好评返 50 元。"并承诺商品没问题，走平台只是"流程需要"。', '{"type":"chat","avatar":"seller","bg":"chat_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 4),
('GW003', '交互事件类', '虚假购物诈骗', 'Yank', 3, '消费维权场景', 2, '海外代购定金', '朋友圈代购："限量 LV 包包，专柜价 2 万，代购价 1.2 万！先付 3000 定金锁定，一周后到货付尾款。"发了大量"客户好评"截图。', '{"type":"task","style":"wechat_moments","highlight":"限量"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 3000, 150, 3000, 0.6, 4);

-- === 中奖退税类 (ZJ) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('ZJ001', '弹窗类', '中奖退税欺诈', 'Kickback', 3, '校园权限场景', 1, '综艺节目中奖', '【系统通知】恭喜您被《中国好声音》抽中二等奖，奖金 15 万元 + 笔记本电脑！请联系领奖热线 400-XXX-XXXX，需先缴纳 8800 元个人所得税。', '{"type":"alert","style":"lottery_fake","icon":"trophy"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 5),
('ZJ002', '社交聊天类', '中奖退税欺诈', 'Spoofing', 2, '社交福利场景', 1, '个税退税通知', '收到"税务局"短信：您有一笔 3880 元个税退税待领取，点击链接 xxx.gov.xx 填写信息。页面要求输入银行卡号、密码、验证码。', '{"type":"chat","avatar":"gov_fake","bg":"official_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 5);

-- === 仿冒网站 APP 类 (FM) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('FM001', '场景界面类', '仿冒网站 APP 诈骗', 'Spoofing', 3, '基础金融场景', 2, '仿冒银行 APP', '收到短信"您的银行卡需升级"，点击链接下载"银行安全助手"APP。界面和真银行几乎一样，登录时输入了账号密码和验证码。', '{"type":"interface","style":"bank_fake","elements":["登录框","验证码输入","升级提示"]} ', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 6),
('FM002', '文档表单类', '仿冒网站 APP 诈骗', 'Information', 3, '法律合同场景', 3, '仿冒政务网站', '办理业务时搜索到"xx 市政务服务网"，网址是 xzwfw.com（官网是 xzwfw.gov.cn）。网站要求填写身份证、银行卡信息"在线办理"。', '{"type":"form","style":"gov_fake","fields":["身份证","银行卡","手机号","验证码"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 6);

-- === 冒充亲友类 (QQ) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('QQ001', '社交聊天类', '亲情牌诈骗', 'Spoofing', 3, '社交福利场景', 1, 'QQ 好友借钱', 'QQ 上"大学同学"突然联系："我朋友住院急用钱，微信转账限额了，能先借我 2000 吗？明天就还！"头像昵称都对，语气也很像。', '{"type":"chat","avatar":"friend_fake","bg":"chat_bg","emotion":"着急"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 7),
('QQ002', '交互事件类', '亲情牌诈骗', 'Repudiation', 3, '社交福利场景', 2, '领导微信借钱', '微信上"老板"让你帮忙转账："我在开会不方便，你先帮我转 5 万给客户，回头给你报销。"发了一个陌生账号给你。', '{"type":"task","style":"wechat_chat","highlight":"老板"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 50000, 150, 50000, 0.8, 7);

-- === 校园贷类 (XYD) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('XYD001', '弹窗类', '虚假购物投资诈骗', 'Kickback', 3, '校园权限场景', 1, '校园贷广告', '【弹窗广告】"大学生专属贷款，无抵押无担保，10 分钟到账！"点击后要求填写个人信息和联系人，号称"额度 5 万，日息仅 0.02%"。', '{"type":"alert","style":"loan_ad","icon":"money"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 8),
('XYD002', '文档表单类', '虚假购物投资诈骗', 'Information', 3, '法律合同场景', 2, '贷款合同陷阱', '某贷款 APP 合同显示"月利率 1%"，但实际有"服务费""管理费""逾期费"等隐藏条款，综合年化利率超过 100%。合同要求你电子签名。', '{"type":"form","style":"contract","fields":["电子签名","人脸识别","通讯录授权"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 8);

-- === 网络游戏类 (YX) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('YX001', '社交聊天类', '虚假购物投资诈骗', 'Low-cost', 2, '社交福利场景', 1, '游戏装备交易', '游戏里有人私聊："我有稀有皮肤，5 折卖你！加 QQ 交易，走微信付款。"发了装备截图，价格确实便宜。', '{"type":"chat","avatar":"gamer","bg":"game_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 500, 100, 500, 0.5, 9),
('YX002', '场景界面类', '仿冒网站 APP 诈骗', 'Spoofing', 3, '社交福利场景', 2, '代充平台', '某"游戏代充网"号称"官方授权，充值 5 折"，要求提供游戏账号密码。充值后账号被盗，装备被转移。', '{"type":"interface","style":"recharge_fake","elements":["账号输入","密码输入","充值金额"]} ', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 200, 150, 200, 0.6, 9);

-- === 征信诈骗类 (ZX) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('ZX001', '社交聊天类', '冒充公检法诈骗', 'Spoofing', 3, '基础金融场景', 2, '客服称征信异常', '接到"京东金融"客服电话："您的学生账户需注销，否则影响征信。请配合操作，将借款额度提现转到指定账户完成注销。"', '{"type":"chat","avatar":"kefu_fake","bg":"chat_bg","emotion":"严肃"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 10),
('ZX002', '交互事件类', '冒充公检法诈骗', 'Information', 3, '职场入职场景', 3, '征信修复骗局', '网上找到"征信修复机构"，对方说交 5000 元"内部渠道费"可以消除逾期记录。要求先付款，承诺 7 个工作日见效。', '{"type":"task","style":"service_ad","highlight":"征信修复"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 5000, 150, 5000, 0.7, 10);

-- === 补充事件 (覆盖更多场景) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('GF001', '按键类', '虚假购物投资诈骗', 'Low-cost', 1, '校园权限场景', 1, '食堂充值优惠', '学校食堂门口海报："扫码进群，充值 100 送 50，限时优惠！"二维码指向个人微信。', '{"type":"button","style":"poster","text":"扫码进群"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 50, 30, 0.3, 4),
('GF002', '弹窗类', '虚假购物投资诈骗', 'Yank', 2, '消费维权场景', 1, '快递理赔', '【短信通知】您的快递丢失，点击链接申请双倍理赔。页面要求填写银行卡信息和验证码。', '{"type":"alert","style":"sms_fake","icon":"package"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 4),
('GF003', '社交聊天类', '交友恋爱诈骗', 'Kickback', 2, '社交福利场景', 2, '理财大师带单', '微信群里"理财大师"分享股票/基金，晒收益图，说"跟着我投，稳赚不赔"。私下推荐某平台。', '{"type":"chat","avatar":"master_fake","bg":"group_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 1000, 100, 1000, 0.5, 3),
('GF004', '场景界面类', '仿冒网站 APP 诈骗', 'Spoofing', 2, '职场入职场景', 2, '虚假招聘网站', '求职时搜索到"知名公司招聘"，网站要求先交"培训费""服装费""保证金"共 3000 元，承诺入职后退还。', '{"type":"interface","style":"recruit_fake","elements":["费用说明","支付入口"]} ', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 3000, 150, 3000, 0.6, 6),
('GF005', '文档表单类', '虚假购物投资诈骗', 'Information', 1, '校园权限场景', 1, '调查问卷陷阱', '"学校调研"要求填写详细家庭信息：父母工作、收入、家庭住址、银行卡号等，声称"用于贫困生评定"。', '{"type":"form","style":"survey","fields":["父母工作","家庭收入","家庭住址","银行卡号"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 50, 30, 0.3, 2);

-- ============================================
-- 第二批反诈科普数据（新增 10 条，ID 11-20）
-- ============================================
INSERT INTO antiFraudKnow (know_id, title, content, verify_question, related_event_ids) VALUES
(11, 'AI 换脸/语音克隆诈骗揭秘', 'AI技术让骗子能伪造你亲人的面容和声音。收到视频电话"借钱"，声音长相都对，但可能是AI合成的！记住：AI换脸难辨真伪，视频通话也未必可信，设置暗号最保险，转账之前二次确认。', '{"question":"收到AI换脸视频电话"借钱"，应该怎么做？","options":["A. 立即转账","B. 用暗语或另一方式单独确认","C. 视频确认就够了","D. 找个中间人转交"],"answer":"B"}', '["AIF001","AIF002","AIF004","AIF005","AIF006"]'),
(12, '数字货币/区块链投资骗局', '"区块链革命""币圈暴富""百倍币"是骗子常用话术。真正的区块链项目不会承诺固定收益，更不会拉人头返利。记住：币圈投资高风险，保本收益是欺诈，去中心化≠无法追回，不懂的技术别碰。', '{"question":"朋友推荐"百倍币"投资项目，以下做法正确的是？","options":["A. 马上投入全部积蓄","B. 先小额试试水","C. 了解项目后理性判断，谨慎投资","D. 拉更多朋友一起赚"],"answer":"C"}', '["BTC001","BTC002","BTC003","BTC004","BTC005"]'),
(13, '健康/疫苗类谣言诈骗', '骗子利用人们对健康的关注，散布疫苗谣言、推销假药、兜售"特效药"。记住：疫苗安全有保障，特效药要认准国药准字，网上神医多骗局，正规医院最靠谱。', '{"question":"网上看到"新冠特效药"和"基因检测"广告，正确的态度是？","options":["A. 立即购买","B. 转发给家人","C. 核查来源，不信不传","D. 先买一点试试"],"answer":"C"}', '["VAC001","VAC002","VAC003","VAC004","VAC005"]'),
(14, '教育培训退费诈骗', '"机构倒闭退学费"是新型诈骗！骗子非法获取你的报课信息，以退费为由诱导贷款、转账或下载不明APP。记住：正规退费走原路，陌生APP不要装，先交钱后退费全是骗局。', '{"question":"收到"某培训机构退费"短信，要求先交"手续费"才能退，应该？","options":["A. 立刻交手续费","B. 联系原机构核实","C. 按短信指引操作","D. 转发给其他学员"],"answer":"B"}', '["EDU001","EDU002","EDU003","EDU004","EDU005"]'),
(15, '演唱会/票务诈骗', '演出旺季票务诈骗高发！"内部票""转让票""折扣票"多为骗局。记住：官方渠道买票最安全，私下交易多骗局，收到"出票失败退费"链接不要点，票务平台也要认准官网。', '{"question":"在二手平台看到"内部渠道演唱会门票"，正确的做法是？","options":["A. 直接微信转账","B. 要求走平台担保交易","C. 先付定金锁定","D. 加价买更保险"],"answer":"B"}', '["TKT001","TKT002","TKT003","TKT004","TKT005"]'),
(16, '元宇宙/VR诈骗揭秘', '元宇宙、虚拟现实等新概念常被骗子包装成投资风口。"元宇宙土地""数字藏品""VR培训"项目背后多为庞氏骗局。记住：新技术≠稳赚钱，虚拟资产难估值，拉人头返利必是盘。', '{"question":"关于元宇宙投资，以下说法正确的是？","options":["A. 新概念肯定能赚钱","B. 承诺固定收益的项目要警惕","C. 早入场就能暴富","D. 跟着大V买不会错"],"answer":"B"}', '["META001","META002","META003","META004","META005"]'),
(17, '屏幕共享/远程控制诈骗', '骗子以"指导操作""核查账户"为名，诱导你开启屏幕共享或远程控制软件。一旦开启，你的手机操作、验证码、密码全被监控。记住：陌生人让你开屏幕共享=诈骗，验证码=最后防线，不给任何人。', '{"question":"客服要求开启手机"屏幕共享"协助操作，应该？","options":["A. 立即开启配合","B. 拒绝并挂断","C. 先开共享再决定","D. 只开一部分"],"answer":"B"}', '["VAR005","VAR011","VAR017"]'),
(18, '航班延误/快递理赔诈骗', '骗子通过非法渠道获取你的购物和出行信息，冒充客服主动理赔。记住：理赔主动找上门的多为骗局，官方渠道自己查，索要验证码和转账的必是诈。', '{"question":"刚购物完就收到"快递丢失赔偿"电话，正确的第一步是？","options":["A. 提供银行卡号","B. 挂断后联系官方客服核实","C. 按对方引导操作","D. 告诉对方验证码"],"answer":"B"}', '["GF002","VAR006","VAR012"]'),
(19, '医保卡/社保卡诈骗', '骗子冒充医保局、社保中心，称你的医保卡"异常""停用""被冻结"，要求提供个人信息或转账到"安全账户"。记住：社保部门不会电话办案，医保卡异常去柜台，安全账户不存在。', '{"question":"接到"医保局"电话说你的医保卡即将停用，应该？","options":["A. 按提示输入确认","B. 挂断后去医保局柜台核实","C. 提供医保卡号给"工作人员"","D. 先转账验资"],"answer":"B"}', '["VAR010","VAR013"]'),
(20, '二维码钓鱼/免费领陷阱', '街头、朋友圈"免费领""扫码送"多是为窃取个人信息或植入病毒。扫了码可能自动转发广告、窃取通讯录、盗刷银行卡。记住：不明二维码不扫，免费福利多陷阱，个人信息值千金。', '{"question":"逛街时看到"扫码免费领玩偶"，正确的做法是？","options":["A. 扫码领取","B. 不扫并远离","C. 帮家人也要一个","D. 转发到朋友圈集赞"],"answer":"B"}', '["GF001","VAR004","VAR020"]');


-- ============================================
-- 第三批风险事件（新增 51 条，覆盖新型诈骗场景）
-- ============================================

-- === AI 换脸/语音克隆诈骗 (AIF) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('AIF001', '社交聊天类', '虚假购物投资诈骗', 'Spoofing', 3, '社交福利场景', 3, 'AI换脸视频通话借钱', '【视频来电】"表哥"打来视频电话，画面中确实是表哥的脸和声音，说话语气也很像："我出车祸了急需5000块，转到我朋友卡上，卡号XXXX。"但你回想，表哥从没这么着急借过钱。', '{"type":"chat","avatar":"cousin_fake","bg":"video_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 11),
('AIF002', '交互事件类', '亲情牌诈骗', 'Repudiation', 3, '高端诈骗场景', 4, 'AI语音克隆勒索', '深夜接到陌生电话，里面传来"女儿"的哭喊声："妈妈救我！"然后一个男声说："你女儿在我们手上，准备20万赎金，不许报警！"电话那头的声音和女儿一模一样。', '{"type":"task","style":"phone_fake","highlight":"女儿哭喊"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 11),
('AIF003', '社交聊天类', '虚假购物投资诈骗', 'Spoofing', 2, '职场入职场景', 3, 'AI换脸相亲诈骗', '交友软件认识的女生，视频聊天时对方AI换脸成美女，声称"家里人生病急需用钱"。每次视频都找借口不开摄像头或只用语音，但会发很多"自拍"照片。', '{"type":"chat","avatar":"beauty_fake","bg":"romantic_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 200, 100, 200, 0.4, 11),
('AIF004', '社交聊天类', '冒充公检法诈骗', 'Spoofing', 3, '基础金融场景', 4, 'AI伪造老板转账指令', '微信收到"老板"语音："我在签约，急需转50万保证金到对公账户XXX，回头补手续。"声音、语气甚至口头禅都和老板一模一样。但老板平时转账都有OA审批流程。', '{"type":"chat","avatar":"boss_fake","bg":"office_bg","emotion":"急促"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 50000, 150, 50000, 0.8, 11),
('AIF005', '弹窗类', '仿冒网站 APP 诈骗', 'Spoofing', 3, '高端诈骗场景', 4, 'AI合成新闻诈骗', '你刷到一条新闻视频，"知名主持人"正在报道某投资平台"国家扶持，收益稳定"，画面和声音很逼真。点击视频下方链接可以注册投资。', '{"type":"alert","style":"news_fake","icon":"tv"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 11),
('AIF006', '场景界面类', '冒充公检法诈骗', 'Spoofing', 2, '消费维权场景', 3, 'AI生成客服语音', '拨打银行客服热线，AI语音完全复刻银行官方的语音提示，引导你输入卡号和密码"核查"。仔细听个别音调略有机械感，但整体非常逼真。', '{"type":"interface","style":"bank_ai","elements":["语音提示","按键输入","身份验证"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 11);

-- === 数字货币/区块链诈骗 (BTC) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('BTC001', '社交聊天类', '虚假购物投资诈骗', 'Kickback', 3, '基础金融场景', 3, '币圈大佬带单', '社群里的"币圈大佬"天天晒收益图："昨天买的SHIB翻了3倍""跟着我，一年财务自由！"私信你拉进一个"VIP带单群"，要求先转ETH"验资"证明实力。', '{"type":"chat","avatar":"crypto_boss","bg":"group_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 1000, 150, 1000, 0.6, 12),
('BTC002', '弹窗类', '虚假购物投资诈骗', 'Kickback', 3, '基础金融场景', 2, '云挖矿骗局', 'APP广告："100元加入云挖矿，日收益2%-5%，稳赚不赔！"宣称有大型矿场，租赁算力挖BTC，收益每日到账。前三天确实能提现小额收益。', '{"type":"alert","style":"mining_ad","icon":"bitcoin"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 100, 150, 100, 0.5, 12),
('BTC003', '场景界面类', '虚假购物投资诈骗', 'Spoofing', 3, '基础金融场景', 3, '虚假交易所', '朋友推荐一个"交易量全球前三"的交易所APP，界面和数据和真交易所很像。充值后看到账户余额翻倍，但提现时提示"账户异常，需缴纳保证金"。', '{"type":"interface","style":"exchange_fake","elements":["行情图","充值入口","提现冻结"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 500, 150, 500, 0.7, 12),
('BTC004', '文档表单类', '虚假购物投资诈骗', 'Information', 2, '法律合同场景', 2, '区块链白皮书投资', '收到一个"革命性区块链项目"白皮书，号称"新一代互联网基础设施"。要求填写身份证、银行卡等信息参与"私募轮投资"，最低1万起投，承诺三个月十倍回报。', '{"type":"form","style":"investment","fields":["身份证","银行卡","投资金额","电子签名"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 10000, 150, 10000, 0.8, 12),
('BTC005', '弹窗类', '虚假购物投资诈骗', 'Yank', 3, '消费维权场景', 2, 'USDT跑分洗钱', '群里有人发布"USDT跑分"任务：用你的USDT帮转账，每笔返利1%。声称"合法兼职""区块链金融创新"。只要把币转到指定钱包就能获得佣金。', '{"type":"alert","style":"task_ad","icon":"money"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 500, 150, 500, 0.5, 12);

-- === 疫苗/健康谣言诈骗 (VAC) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('VAC001', '弹窗类', '虚假购物投资诈骗', 'Kickback', 3, '社交福利场景', 2, '新冠特效药推销', '收到短信："新冠口服特效药，国家药监局特批，库存有限！"点击链接进入页面，要求先付款后发货，号称"院士研发，三天转阴"，售价2980元一盒。', '{"type":"alert","style":"medicine_ad","icon":"pill"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 2980, 150, 2980, 0.8, 13),
('VAC002', '文档表单类', '仿冒网站 APP 诈骗', 'Spoofing', 1, '社交福利场景', 1, '疫苗副作用调查', '群里有人转发"国家疾控中心疫苗后遗症补偿"链接：填写个人信息可申请5万元补偿金。页面需要上传身份证、银行卡、手机验证码。', '{"type":"form","style":"gov_fake","fields":["身份证","银行卡","验证码","住址"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 50, 30, 0.3, 13),
('VAC003', '社交聊天类', '虚假购物投资诈骗', 'Spoofing', 2, '消费维权场景', 2, '基因检测骗局', '网上看到"唾液基因检测"，298元即可检测癌症风险、天赋基因等200项指标。客服发来

一个权威报告链接，\"国家基因库认证，限时特价\"。要求在线支付并填写详细住址。', '{"type":"chat","avatar":"doctor_fake","bg":"official_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 298, 100, 298, 0.5, 13),
('VAC004', '弹窗类', '虚假购物投资诈骗', 'Low-cost', 2, '社交福利场景', 2, '保健品骗局', '朋友圈看到\"某医学博士推荐\"的保健品广告：\"天然植物提取，根治高血压糖尿病，无效退款！\"一疗程1980元，买三送一。还附了很多\"患者康复\"的聊天截图。', '{"type":"alert","style":"health_ad","icon":"leaf"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 1980, 100, 1980, 0.6, 13),
('VAC005', '社交聊天类', '虚假购物投资诈骗', 'Spoofing', 3, '消费维权场景', 3, '专家在线问诊', '手机上弹出\"三甲医院名医在线问诊\"广告，知名专家的头像和简介看起来都很正规。添加微信后，对方要求先付500元\"挂号费\"，然后推荐了2000元的\"特效中药\"。', '{"type":"chat","avatar":"expert_fake","bg":"hospital_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 2500, 150, 2500, 0.7, 13);

-- === 教育培训退费诈骗 (EDU) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('EDU001', '弹窗类', '虚假购物投资诈骗', 'Kickback', 3, '校园权限场景', 2, '培训退费通知', '收到短信：\"你报名的XX网课机构已倒闭，现在办理退费，已交费用全额返还！\"要求添加QQ群，群内有\"退费专员\"引导，需要先交20%\"税费\"才能退费。', '{"type":"alert","style":"official_fake","icon":"seal"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 14),
('EDU002', '社交聊天类', '虚假购物投资诈骗', 'Information', 2, '校园权限场景', 2, '学历提升骗局', '"XX大学招生办"来电：\"我们有名校内部指标，大专升本科只需1.5年，学信网可查！\"对方说需要交8000元\"内部操作费\"，并索要身份证复印件和照片。', '{"type":"chat","avatar":"school_fake","bg":"office_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 8000, 150, 8000, 0.7, 14),
('EDU003', '交互事件类', '虚假购物投资诈骗', 'Kickback', 3, '职场入职场景', 3, '考证包过', '网上看到\"XX资格证包过，不过全额退款！\"客服承诺提供考试原题和答案，费用3000元。要求先付一半定金，考过再付余款。发了很多\"通过学员\"的聊天记录。', '{"type":"task","style":"service_ad","highlight":"包过"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 3000, 150, 3000, 0.6, 14),
('EDU004', '场景界面类', '仿冒网站 APP 诈骗', 'Spoofing', 3, '基础金融场景', 3, '网课退费APP', '你收到\"退费中心\"发来的链接，下载了一个名为\"清退办\"的APP。APP界面看起来很正规，有你的\"退费余额\"显示。客服说需要先\"购买证券\"完成交易才能提现退费。', '{"type":"interface","style":"refund_fake","elements":["退费余额","购买证券入口","提现按钮"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 2000, 150, 2000, 0.8, 14),
('EDU005', '文档表单类', '虚假购物投资诈骗', 'Information', 2, '校园权限场景', 2, '教育分期陷阱', '"0元入学，先学后付！"报名时对方引导你签了一份\"教育分期合同\"，实际上是用你的身份信息在网贷平台贷款。合同写得很复杂，充满了专业术语。', '{"type":"form","style":"contract","fields":["身份证","银行卡","手机号","电子签名"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 14);

-- === 演唱会/票务诈骗 (TKT) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('TKT001', '社交聊天类', '虚假购物投资诈骗', 'Low-cost', 2, '二手交易场景', 2, '演唱会门票转让', '某明星演唱会一票难求。你在微博看到有人转票：\"内场VIP票原价1280，现价1800两张，确认后改地址。\"卖家说走平台太慢，要求微信先付款后发电子票。', '{"type":"chat","avatar":"seller_fake","bg":"chat_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 1800, 100, 1800, 0.6, 15),
('TKT002', '场景界面类', '仿冒网站 APP 诈骗', 'Spoofing', 3, '二手交易场景', 2, '仿冒购票网站', '搜索引擎置顶广告显示\"大麦网\"购票链接，点进去页面和真大麦网一模一样。选座、付款流程齐全，但付款后的\"电子票\"二维码扫描显示无效。网址是 damai-xxx.com。', '{"type":"interface","style":"ticket_fake","elements":["选座界面","付款页面","电子票"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 1280, 150, 1280, 0.5, 15),
('TKT003', '社交聊天类', '虚假购物投资诈骗', 'Yank', 3, '消费维权场景', 3, '内部渠道购票', '黄牛私信：\"我朋友在票务公司上班，有内部预留票，加价300就能拿！\"给你看了\"内部系统\"截图和订单信息。要求先付全款，演出当天现场取票。', '{"type":"chat","avatar":"scalper_fake","bg":"chat_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 1580, 150, 1580, 0.7, 15),
('TKT004', '弹窗类', '虚假购物投资诈骗', 'Kickback', 2, '消费维权场景', 2, '退票手续费', '你买了一张门票但因故无法前往。在二手平台发布转票信息后，有人联系说：\"我有担保平台，你注册后发布，买家付款到我平台，保证安全。\"但平台要你先交\"保证金\"才能收款。', '{"type":"alert","style":"platform_fake","icon":"ticket"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 500, 100, 500, 0.5, 15),
('TKT005', '交互事件类', '虚假购物投资诈骗', 'Low-cost', 2, '二手交易场景', 1, '二手票平台钓鱼', '你在\"转转\"看到超低价演唱会门票，卖家信用很高。要求用QQ联系，发来一个\"转转担保交易\"链接。页面很真，但其实是钓鱼网站，登录后账号密码被窃取。', '{"type":"task","style":"link_fake","highlight":"担保交易"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 15);

-- === 元宇宙/VR 诈骗 (META) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('META001', '社交聊天类', '虚假购物投资诈骗', 'Kickback', 3, '高端诈骗场景', 4, '元宇宙土地投资', '社群推广\"元宇宙首块土地发售\"：\"未来虚拟土地价值百万，现在只需999 USDT即可认购！项目方已获XX资本投资！\"客服每天发收益图和土地升值预测，早鸟优惠只剩最后3天。', '{"type":"chat","avatar":"meta_fake","bg":"group_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 10000, 150, 10000, 0.8, 16),
('META002', '弹窗类', '虚假购物投资诈骗', 'Low-cost', 2, '消费维权场景', 2, 'VR设备低价团购', '弹窗广告：\"原价3999元的VR一体机，厂价直销仅999元！限时限量！\"链接到一个精致商城页面，支持货到付款。但付款后两周未发货，客服失联。', '{"type":"alert","style":"product_ad","icon":"vr"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 999, 100, 999, 0.5, 16),
('META003', '场景界面类', '仿冒网站 APP 诈骗', 'Spoofing', 2, '职场入职场景', 3, '虚拟现实培训骗局', '"VR虚拟现实培训班，月薪过万不是梦！"对方发来一个官方网站，展示"学员作品"和"就业案例"。要求先交6800元学费，可办理"教育分期"。培训后发现课程是网上免费资源拼凑的。', '{"type":"interface","style":"edu_fake","elements":["官网展示","课程介绍","报名入口"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 6800, 150, 6800, 0.7, 16),
('META004', '弹窗类', '虚假购物投资诈骗', 'Kickback', 3, '基础金融场景', 3, '数字藏品投资', '"稀缺数字藏品限量发行，抢到就是赚到！"平台发售"十二生肖"NFT，单价998元，号称"三个月后上交易所，至少翻10倍"。很多人在群里晒转账截图。', '{"type":"alert","style":"nft_ad","icon":"art"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 998, 150, 998, 0.6, 16),
('META005', '交互事件类', '虚假购物投资诈骗', 'Yank', 3, '基础金融场景', 2, '元宇宙游戏充值', '一款\"元宇宙游戏\"宣传\"边玩边赚\"，买虚拟装备就能获得代币收益。客服引导你先充值200元买\"新手礼包\"，然后一步步诱导你充值更多买\"高级矿机\"。', '{"type":"task","style":"game_fake","highlight":"边玩边赚"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 200, 150, 200, 0.5, 16);

-- === 新型变种事件 (VAR) ===
INSERT INTO riskEvents (event_id, event_type, fraud_type, briskly_point, risk_level, scene_type, min_role_level, title, content, style_config, button_config, cost_invest, success_reward, fail_penalty, fail_penalty_rate, anti_fraud_id) VALUES
('VAR001', '交互事件类', '虚假购物投资诈骗', 'Low-cost', 2, '校园兼职场景', 1, '关注点赞刷单', '群里有\"轻松兼职\"：关注公众号、点赞视频号，每单2-5元，日结！前10单确实赚了50元。然后对方说\"有高佣金任务\"：需要先垫付300元，完成后返400元。', '{"type":"task","style":"group_msg","highlight":"高佣金"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 300, 100, 300, 0.5, 2),
('VAR002', '社交聊天类', '冒充公检法诈骗', 'Spoofing', 3, '社交福利场景', 2, '冒充防疫人员', '有人穿防护服敲门，自称社区防疫工作人员：\"大数据显示你是密接，需要立即去集中隔离！\"但要求你先交\"隔离押金\"2000元，并提供身份证和银行卡号\"登记\"。', '{"type":"chat","avatar":"epi_fake","bg":"door_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 10),
('VAR003', '弹窗类', '虚假购物投资诈骗', 'Spoofing', 3, '社交福利场景', 2, '核酸检测诈骗', '收到短信：\"您的核酸检测结果异常，点击链接查看详情。\"链接页面要求输入姓名、身份证、手机号、银行卡号\"身份验证\"。页面还有\"国家卫健委\"的logo。', '{"type":"alert","style":"gov_fake","icon":"health"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 13),
('VAR004', '文档表单类', '仿冒网站 APP 诈骗', 'Information', 2, '社交福利场景', 1, '运营商积分兑换', '收到\"10086\"短信：\"您的积分即将过期，点击兑换丰厚礼品！\"链接页面和移动官网很像，要求填写手机号、服务密码、身份证号才能兑换。', '{"type":"form","style":"tel_fake","fields":["手机号","服务密码","身份证"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 20),
('VAR005', '场景界面类', '冒充公检法诈骗', 'Information', 3, '基础金融场景', 3, '屏幕共享诈骗', '冒充客服人员说：\"我们需要帮您操作退款，请下载\"云会议\"APP并开启屏幕共享。\"开启后，对方看到你手机上的银行卡号、密码、验证码，然后你的钱被转走。', '{"type":"interface","style":"share_screen","elements":["会议邀请","屏幕共享开关","验证码输入"]}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 17),
('VAR006', '社交聊天类', '虚假购物投资诈骗', 'Spoofing', 3, '消费维权场景', 2, '快递退款钓鱼', '收到\"菜鸟驿站\"短信：\"您的包裹运输中丢失，点击链接申请赔付。\"添加微信后，客服发来一个\"理赔中心\"小程序链接，要求填写银行卡号和短信验证码。', '{"type":"chat","avatar":"logistics_fake","bg":"chat_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 18),
('VAR007', '社交聊天类', '虚假购物投资诈骗', 'Low-cost', 2, '社交福利场景', 1, '小红书私信骗局', '小红书收到私信：\"姐妹你的照片好好看，可以签约当模特吗？需要先交500元\"推广费\"，每个月保底接单5000+！\"还发来很多\"签约模特\"的收款截图。', '{"type":"chat","avatar":"agent_fake","bg":"social_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 500, 100, 500, 0.5, 4),
('VAR008', '弹窗类', '虚假购物投资诈骗', 'Kickback', 2, '社交福利场景', 2, '直播打赏骗局', '抖音直播间里，\"大哥\"疯狂刷火箭，主播激动喊麦：\"感谢大哥！今天抽奖送iPhone，榜一必中！\"弹幕里\"中奖大哥\"纷纷晒出收到手机的截图。', '{"type":"alert","style":"live_fake","icon":"gift"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 500, 100, 500, 0.4, 4),
('VAR009', '社交聊天类', '虚假购物投资诈骗', 'Spoofing', 2, '二手交易场景', 2, '闲鱼验货宝骗局', '闲鱼上买家说：\"我走验货宝，你把货发到验货中心，我付全款。\"卖家发来一个\"闲鱼验货宝\"的二维码，扫进去是假的验货平台。要求先交\"验货保证金\"才能发货。', '{"type":"chat","avatar":"buyer_fake","bg":"chat_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 500, 100, 500, 0.5, 4),
('VAR010', '社交聊天类', '冒充公检法诈骗', 'Spoofing', 3, '基础金融场景', 3, '冒充公检法升级版', '来电显示为\"110\"，对方自称\"经侦支队\"：\"你的身份证被冒用注册公司，涉及洗钱案！\"要求你下载\"国家反诈中心\"清查APP（假冒的），然后进行\"资金核查\"。', '{"type":"chat","avatar":"police_fake","bg":"office_bg","emotion":"严肃"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 1),
('VAR011', '交互事件类', '冒充公检法诈骗', 'Information', 2, '校园权限场景', 2, '手机卡注销骗局', '收到\"运营商\"短信：\"您的手机号涉嫌发送诈骗短信，即将被永久停机。如需处理请点击链接。\"点进去要求输入身份证号、银行卡号和手机验证码\"实名验证\"。', '{"type":"task","style":"sms_fake","highlight":"停机"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 17),
('VAR012', '交互事件类', '虚假购物投资诈骗', 'Spoofing', 3, '消费维权场景', 3, '航班延误理赔', '刚订完机票就收到\"航空公司\"短信：\"您乘坐的XX航班因机械故障取消，请办理退改签，补偿300元延误险。\"客服电话指导你操作，要求提供银行卡号接收\"补偿金\"。', '{"type":"task","style":"sms_fake","highlight":"航班取消"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 18),
('VAR013', '弹窗类', '冒充公检法诈骗', 'Spoofing', 3, '校园权限场景', 2, '医保卡停用短信', '收到\"医保局\"短信：\"您的医保卡因异常消费被停用，请点击链接在线恢复。\"链接页面要求填写身份证号、医保卡号、银行卡号和密码，用于\"身份核验\"。', '{"type":"alert","style":"gov_fake","icon":"health"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 19),
('VAR014', '社交聊天类', '冒充公检法诈骗', 'Spoofing', 3, '基础金融场景', 3, '微信百万保障', '来电自称\"微信客服\"：\"您的百万保障免费试用已到期，下月起每月扣2000元。如需取消请按指引操作。\"然后要求你打开微信钱包\"操作取消\"，实际是在引导转账。', '{"type":"chat","avatar":"kefu_fake","bg":"chat_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 1),
('VAR015', '按键类', '仿冒网站 APP 诈骗', 'Low-cost', 1, '消费维权场景', 1, '共享充电宝陷阱', '扫码借充电宝，跳出的页面要求你\"授权个人信息\"包括通讯录、相册、位置。授权后手机自动安装了一些不明APP，开始推送赌博广告。', '{"type":"button","style":"qr_fake","text":"扫码授权"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 50, 30, 0.3, 20),
('VAR016', '弹窗类', '虚假购物投资诈骗', 'Yank', 2, '消费维权场景', 2, '酒店色情卡片', '酒店房间门缝塞进来一张小卡片，印着性感美女和电话。如果你打电话，对方会要求先发红包\"定金\"，然后一步步诱导转账更多\"服务费\"。', '{"type":"alert","style":"card_fake","icon":"phone"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 4),
('VAR017', '社交聊天类', '虚假购物投资诈骗', 'Kickback', 3, '校园兼职场景', 2, '短视频刷单升级', '某视频平台私信：\"帮博主点赞评论，每单8元，工资日结！\"加入群后，任务从点赞变成了\"预充值返利\"，先转200元到指定账户，系统自动返260元，但金额越滚越大。', '{"type":"chat","avatar":"boss_fake","bg":"group_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 200, 150, 200, 0.5, 2),
('VAR018', '社交聊天类', '冒充公检法诈骗', 'Spoofing', 3, '高端诈骗场景', 4, '境外电话冒充客服', '来电显示+1（美国号码），对方流利的中文自称\"亚马逊中国客服\"，准确说出你最近买过的东西和地址。然后说\"由于员工操作失误，已将你设为代理商，每年扣费6000元\"。', '{"type":"chat","avatar":"kefu_oversea","bg":"chat_bg"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 150, 100, 0.5, 1),
('VAR019', '弹窗类', '中奖退税欺诈', 'Kickback', 2, '社交福利场景', 1, 'AI生成中奖信息', '"尊敬的用户，您被XX平台抽中年度锦鲤大奖：iPhone16ProMax+88888元现金！点击链接确认领取。"链接页面用AI生成的明星\"手写\"祝词，看起来很真实。', '{"type":"alert","style":"lottery_fake","icon":"gift"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 5),
('VAR020', '按键类', '仿冒网站 APP 诈骗', 'Information', 2, '社交福利场景', 1, '二维码钓鱼', '你在餐馆扫码点餐，二维码被偷偷替换了。扫码后跳转到仿冒的支付页面，输入了银行卡号和密码。真正的点餐系统反而需要重新扫正确的码。', '{"type":"button","style":"qr_fake","text":"扫码点餐"}', '{"buttons":[{"text":"安全","risk":1},{"text":"低风险","risk":2},{"text":"高风险","risk":3}]}', 0, 100, 50, 0.3, 20);
